[package]
name = "beta-red"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
js-sys = "0.3.82"

[lib]
crate-type = ["cdylib", "rlib"]
